name: keras2.7
channels:
  - menpo
  - defaults
dependencies:
  - alabaster=0.7.12=py27_0
  - asn1crypto=0.24.0=py27_0
  - astroid=1.6.5=py27_0
  - babel=2.6.0=py27_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py27_0
  - blas=1.0=mkl
  - bleach=3.0.2=py27_0
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.11.29=py27_0
  - cffi=1.11.5=py27he75722e_1
  - chardet=3.0.4=py27_1
  - cloudpickle=0.6.1=py27_0
  - configparser=3.5.0=py27h5117587_0
  - cryptography=2.4.2=py27h1ba5d50_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py27_0
  - docutils=0.14=py27hae222c1_0
  - entrypoints=0.2.3=py27_2
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=0.9.39=1
  - hdf5=1.8.17=2
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py27_0
  - imagesize=1.1.0=py27_0
  - intel-openmp=2019.1=144
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27h89fb69b_0
  - isort=4.3.4=py27_0
  - jedi=0.13.2=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py27_0
  - jupyter_client=5.2.4=py27_0
  - jupyter_core=4.4.0=py27_0
  - lazy-object-proxy=1.3.1=py27h14c3975_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.1.0=py27h7b6447c_0
  - mccabe=0.6.1=py27_1
  - mistune=0.8.4=py27h7b6447c_0
  - mkl=2019.1=144
  - nbconvert=5.3.1=py27_0
  - nbformat=4.4.0=py27_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.11.3=py27h3dfced4_4
  - numpydoc=0.8.0=py27_0
  - openssl=1.1.1a=h7b6447c_0
  - packaging=18.0=py27_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py27_1
  - parso=0.3.1=py27_0
  - pathlib2=2.3.3=py27_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pip=18.1=py27_0
  - pixman=0.36.0=h7b6447c_0
  - prompt_toolkit=1.0.15=py27h1b593e1_0
  - psutil=5.4.8=py27h7b6447c_0
  - ptyprocess=0.6.0=py27_0
  - pycodestyle=2.4.0=py27_0
  - pycparser=2.19=py27_0
  - pyflakes=2.0.0=py27_0
  - pygments=2.3.1=py27_0
  - pylint=1.9.2=py27_0
  - pyopenssl=18.0.0=py27_0
  - pyparsing=2.3.0=py27_0
  - pyqt=5.9.2=py27h05f1152_2
  - pysocks=1.6.8=py27_0
  - python=2.7.15=h9bab390_6
  - python-dateutil=2.7.5=py27_0
  - pytz=2018.7=py27_0
  - pyzmq=17.1.2=py27h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.5.5=py27_0
  - qtconsole=4.4.3=py27_0
  - qtpy=1.5.2=py27_0
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py27_0
  - rope=0.11.0=py27_0
  - scandir=1.9.0=py27h14c3975_0
  - setuptools=40.6.3=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - snowballstemmer=1.2.1=py27h44e2768_0
  - sphinx=1.8.2=py27_0
  - sphinxcontrib=1.0=py27_1
  - sphinxcontrib-websupport=1.1.0=py27_1
  - spyder=3.3.2=py27_0
  - spyder-kernels=0.3.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py27h7b6447c_0
  - traitlets=4.3.2=py27_0
  - typing=3.6.6=py27_0
  - urllib3=1.24.1=py27_0
  - wcwidth=0.1.7=py27h9e3e1ab_0
  - webencodings=0.5.1=py27_1
  - wheel=0.32.3=py27_0
  - wrapt=1.10.11=py27h14c3975_2
  - wurlitzer=1.0.2=py27_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - opencv3=3.2.0=np111py27_0
  - pip:
    - absl-py==0.7.0
    - astor==0.7.1
    - backports.weakref==1.0.post1
    - funcsigs==1.0.2
    - gast==0.2.2
    - grpcio==1.18.0
    - h5py==2.9.0
    - html5lib==0.9999999
    - keras==2.1.4
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - keras-resnet==0.1.0
    - markdown==3.0.1
    - mock==2.0.0
    - pbr==5.1.1
    - protobuf==3.6.1
    - pyyaml==3.13
    - scipy==1.2.0
    - tensorboard==1.12.2
    - tensorflow==1.3.0
    - tensorflow-gpu==1.3.0
    - tensorflow-tensorboard==0.1.8
    - termcolor==1.1.0
    - werkzeug==0.14.1
    - pillow==6.0.0
prefix: /home/salman/anaconda3/envs/keras2.7

